"""remove wo parts equipment workflow state

Revision ID: 3fa667fc39b4
Revises: afd998d01c9f
Create Date: 2026-03-16 14:22:56.801013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fa667fc39b4'
down_revision: Union[str, None] = 'afd998d01c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_issue', 'date_issued',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('purchase_request', 'requestor_name')
    op.drop_column('work_order_equipment', 'workflow_state')
    op.drop_column('work_order_parts', 'workflow_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_parts', sa.Column('workflow_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('work_order_equipment', sa.Column('workflow_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('purchase_request', sa.Column('requestor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('item_issue', 'date_issued',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
