"""rename model.model_name to name

Revision ID: a2f3e3ff8feb
Revises: 4c2a6d9e1f0b
Create Date: 2026-04-22 22:49:12.395414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f3e3ff8feb'
down_revision: Union[str, None] = '4c2a6d9e1f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RfqLine',
    sa.Column('rfq_id', sa.String(length=255), nullable=True),
    sa.Column('pr_line', sa.String(length=255), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('last_modified_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('asset', 'item_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('inventory', 'item_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('inventory_workflow_state_fkey', 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'workflow_state')
    op.add_column('maintenance_condition', sa.Column('threshold_value', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('model', 'model_name')
    op.alter_column('work_order_activity', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_order_activity', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('model', sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('model', 'name')
    op.drop_column('maintenance_condition', 'threshold_value')
    op.add_column('inventory', sa.Column('workflow_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('inventory_workflow_state_fkey', 'inventory', 'core_workflow_states', ['workflow_state'], ['id'])
    op.alter_column('inventory', 'item_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('asset', 'item_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_table('RfqLine')
    # ### end Alembic commands ###
